const employees = [
  {
    id: 1,
    firstname: "Aarav",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Submit project report",
        description: "Compile and submit the final report for Project Alpha.",
        date: "2025-06-10",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Attend team meeting",
        description: "Weekly sync-up with the product team.",
        date: "2025-06-11",
        category: "Meetings",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Fix login bug",
        description: "Resolve login failure on mobile view.",
        date: "2025-06-08",
        category: "Development",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Code refactoring",
        description: "Refactor old code for better readability.",
        date: "2025-06-12",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Backup database",
        description: "Schedule full backup of all project databases.",
        date: "2025-06-13",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 2,
    firstname: "Ishaan",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Design landing page",
        description: "Create initial design for new landing page.",
        date: "2025-06-09",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Review PRs",
        description: "Review pending pull requests on GitHub.",
        date: "2025-06-07",
        category: "Code Review",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Fix broken icons",
        description: "Replace missing icons on header.",
        date: "2025-06-08",
        category: "Frontend",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Team collaboration board",
        description: "Create shared Figma board for the UI team.",
        date: "2025-06-10",
        category: "Design",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Write unit tests",
        description: "Add Jest tests for recent components.",
        date: "2025-06-11",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 3,
    firstname: "Kabir",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Create database schema",
        description: "Design schema for new user module.",
        date: "2025-06-12",
        category: "Database",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Client feedback",
        description: "Call with client to discuss feedback.",
        date: "2025-06-06",
        category: "Client Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Optimize queries",
        description: "Improve performance of user queries.",
        date: "2025-06-08",
        category: "Backend",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Update documentation",
        description: "Add new endpoints to API docs.",
        date: "2025-06-09",
        category: "Documentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Setup staging environment",
        description: "Deploy app to staging for UAT.",
        date: "2025-06-13",
        category: "Deployment",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Refactor login module",
        description: "Separate logic into reusable components.",
        date: "2025-06-14",
        category: "Frontend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 3,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 4,
    firstname: "Neha",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Security audit",
        description: "Check project for vulnerabilities.",
        date: "2025-06-10",
        category: "Security",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Onboard new intern",
        description: "Provide system access and overview.",
        date: "2025-06-08",
        category: "HR",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Prepare pitch deck",
        description: "Create slides for upcoming investor meeting.",
        date: "2025-06-11",
        category: "Business",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Check compliance policy",
        description: "Ensure updated privacy terms are shared.",
        date: "2025-06-12",
        category: "Legal",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Book venue for workshop",
        description: "Finalize and book the venue.",
        date: "2025-06-13",
        category: "Operations",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 5,
    firstname: "Priya",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "QA testing",
        description: "Test new features for bugs.",
        date: "2025-06-09",
        category: "Testing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Sprint planning",
        description: "Plan tasks for next sprint.",
        date: "2025-06-07",
        category: "Agile",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Fix dashboard layout",
        description: "Resolve alignment issues on dashboard.",
        date: "2025-06-10",
        category: "Frontend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Mobile responsiveness",
        description: "Ensure dashboard is mobile-friendly.",
        date: "2025-06-11",
        category: "Frontend",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Bug triage",
        description: "Review and prioritize reported bugs.",
        date: "2025-06-12",
        category: "QA",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskNumbers: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
  },
];

const admin = [
  {
    id: 1,
    firstname:"Admin",
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
